version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=5000
      - NODE_ENV=development
      - JWT_SECRET=aria_test_secret_key
      - JWT_EXPIRE=30d
      - USE_MONGODB=false
      - SOLANA_NETWORK=devnet
      - SOLANA_RPC_URL=https://api.devnet.solana.com
      - ARI_TOKEN_ADDRESS=AriTkbS9TLpYMGVT3dYYbLjKMiPqzPpXyv97uij1dLP
      - CORS_ORIGIN=http://localhost:3000

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api 